application: kaffeeshare
version: alpha2go
runtime: go
api_version: go1
automatic_scaling:
  max_concurrent_requests: 10
default_expiration: "10m"
inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/static/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: _go_app
- url: /_ah/mail/
  script: _go_app
