runtime:                   go111
automatic_scaling:
  min_idle_instances:      0
  max_idle_instances:      automatic  # default value
  min_pending_latency:     30ms      # default value
  max_pending_latency:     automatic
  max_concurrent_requests: 15
default_expiration:        "10m"
inbound_services:
- mail

handlers:
- url:                     /robots.txt
  static_files:            static/robots.txt
  upload:                  static/robots.txt
- url:                     /favicon.ico
  static_files:            static/favicon.ico
  upload:                  static/favicon.ico
  expiration:              "24h"

- url:                     /static
  static_dir:              static

# Just to prevent the queries to the old RSS feed URL hitting the app
- url:                     /feed
  static_dir:              static
  expiration:              "48h"

#- url:                     /_ah/mail/
#  script:                  _go_app

# Cron jobs
#- url:                     /c/.*
#  script:                  _go_app
#  login:                   admin

# Task queues
#- url:                     /t/.*
#  script:                  _go_app
#  login:                   admin
#- url:                     /_ah/queue/go/delay
#  script:                  _go_app
#  login:                   admin

# Admin URLs
#- url:                     /a/.*
#  script:                  _go_app
#  login:                   admin

# Catch the rest
#- url:                     /.*
#  script:                  _go_app
